## Takes input from Google drive spreadsheet to generate files for iOS and Android
## Needs var spreadsheet-id for generation
inputs:
  # This repo
  - name: scripts
  # Folder containg Drive config.json, named content
  - name: drive-config

outputs: 
  # Strings files will be placed here
  - name: results

params:
  # Config file path to authenticate on drive
  DRIVE_CONFIG: drive-config/content

run:
  path: ruby
  args: [ scripts/main.rb, ((spreadsheet-id))]

platform: linux
image_resource:
  type: registry-image
  source:
    repository: registry.infra.yoti.com/android/task-ruby-alpine